homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: 52.262845
  longitude: 10.516442
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  #  auth_providers:
  #    - type: trusted_networks

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: 192.168.178.4:8123
  #  api_password: !secret api_password
  #  trusted_networks:
  #    - 127.0.0.1
  #   - ::1
  #    - 192.0.0.0/32
  #    - 192.168.178.201
  #    - fd00::/8
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
        
media_player:
  - platform: spotify
    client_id: 'e487f5ed1c3a4be084b3deb9620e15a0'
    client_secret: 'f66d47cc1cda43a2906926ea1d299509'

  - platform: firetv
    name: FireTV
    host: 192.168.178.3
    adbkey: "/home/homeassistant/.homeassistant/keys/adbkey"

shopping_list:

sensor: !include sensors.yaml

#weather:
#  - platform: darksky
#    api_key: !secret dark_sky_api_key
#    mode: daily
#    language: de

# Input for hue scenes
input_select:
  bedroom_scenes:
    name: Szenen
    options:
      - Entspannen
      - Lesen
      - Konzentrieren
      - Nordlichter
      - Hell
      - Gedimmt
      - Nachtlicht
      - Tropendämmerung
      - Energie tanken
      - Sonnenuntergang Savanne
      - Frühlingsblüten
    initial: Hell
    icon: mdi:creation

  lamp:
    name: Zimmer
    options:
      - Wohnzimmer
      - Schlafzimmer
    initial: Wohnzimmer
    icon: mdi:door

# Input for hue wake-up automation
input_boolean:
  wakeup_enabled:
    name: "Wake-up Modus"
    initial: off
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "Wake-up am Wochenende"
    initial: off
    icon: mdi:calendar-multiselect
  kino_modus:
    name: "Kino Modus"
    initial: off
    icon: mdi:theater

input_datetime:
  wakeup_time:
    name: "Starte Licht ab"
    has_time: true
    has_date: false
    initial: "06:51"

input_number:
  wakeup_duration:
    name: "Dauer"
    icon: mdi:clock-in
    initial: 20
    min: 0
    max: 55
    step: 5

  brightness_schlafzimmer:
    name: "Hellightkeit Schlafzimmer"
    icon: mdi:brightness-6
    initial: 255
    min: 1
    max: 255
    step: 10

  brightness_wohnzimmer:
    name: "Helligkeit Wohnzimmer"
    icon: mdi:brightness-6
    initial: 255
    min: 1
    max: 255
    step: 10

# Device trackers
device_tracker:
  - platform: fritz
    host: 192.168.178.1
    #    password: !secret fritzbox_password
    interval_seconds: 30

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

