homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.262845
  longitude: 10.516442
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: hassbian.local:8123
  #  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.0.0.0/32
    - 192.168.178.201
    - fd00::/8
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  - platform: fritzbox_netmonitor

# Weather dark sky
#weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    language: de
    update_interval: 300
    forecast:
      - 1
    monitored_conditions:
      - temperature
      - apparent_temperature
      - temperature_min
      - temperature_max
      - humidity
      - precip_probability
      - precip_intensity
      - precip_type
      - wind_speed
      - wind_bearing
      - pressure
      - icon
      - summary
      - daily_summary

            
            
# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Device trackers
device_tracker:
  - platform: fritz
    #    password: !secret fritzbox_password
    interval_seconds: 30

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

