$(function(){ //DOM Ready

    function navigate(url)
    {
        window.location.href = url;
    }

    $(document).attr("title", "Main Panel");
    content_width = (121 + 5) * 10 + 5
    $('.gridster').width(content_width)
    $(".gridster ul").gridster({
        widget_margins: [5, 5],
        widget_base_dimensions: [121, 122],
        avoid_overlapped_widgets: true,
        max_rows: 6,
        max_size_x: 10,
        shift_widgets_up: false
    }).data('gridster').disable();
    
    // Add Widgets

    var gridster = $(".gridster ul").gridster().data('gridster');
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-nav-main" id="default-nav-main"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 1, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label" id="default-label"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 6, 1, 2, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-reload" id="default-reload"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 8, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseclock-default-clock" id="default-clock"><h1 class="date"data-bind="text: date, attr: {style: date_style}"></h1><h2 class="time" data-bind="text: time, attr: {style: time_style}"></h2></div></li>', 2, 1, 9, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-nav-weather" id="default-nav-weather"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 1, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-weather-label" id="default-weather-label"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 2, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseentitydisplay-default-temperature-now" id="default-temperature-now"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseiconsensor-default-weather-icon-now" id="default-weather-icon-now"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseentitydisplay-default-daily-forecast" id="default-daily-forecast"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 6, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baserss-default-ts-rss-feed" id="default-ts-rss-feed"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><h1 class="text" data-bind="html: text, attr:{ style: text_style}"></h1><h1 class="description" data-bind="html: description, attr:{ style: text_style}"></h1></div></li>', 3, 1, 8, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-nav-spacer" id="default-nav-spacer"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 3, 1, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-modi-title" id="default-modi-title"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 2, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-kino-bool" id="default-kino-bool"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-wakeup-bool" id="default-wakeup-bool"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 6, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-wakeup-weekend" id="default-wakeup-weekend"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 7, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baserss-default-world-rss-feed" id="default-world-rss-feed"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><h1 class="text" data-bind="html: text, attr:{ style: text_style}"></h1><h1 class="description" data-bind="html: description, attr:{ style: text_style}"></h1></div></li>', 3, 1, 8, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-hue-scene-label" id="default-hue-scene-label"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 2, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseselect-default-scene-select" id="default-scene-select"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="styled-select" data-bind="attr:{style: selectcontainer_style}">  <select data-bind="options: inputoptions, value: selectedoption, attr:{style: select_style}">  </select></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 4, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseselect-default-room-select" id="default-room-select"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="styled-select" data-bind="attr:{style: selectcontainer_style}">  <select data-bind="options: inputoptions, value: selectedoption, attr:{style: select_style}">  </select></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 6, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baserss-default-hn-rss-feed" id="default-hn-rss-feed"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><h1 class="text" data-bind="html: text, attr:{ style: text_style}"></h1><h1 class="description" data-bind="html: description, attr:{ style: text_style}"></h1></div></li>', 3, 1, 8, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label-hue-wz" id="default-label-hue-wz"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 2, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-label-licht" id="default-label-licht"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 2, 1, 4, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseinputnumber-default-bri-wohnzimmer" id="default-bri-wohnzimmer"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="slidercontainer" data-bind="attr:{style: slidercontainer_style}"><input type="range" data-bind="attr: {min: MinValue, max: MaxValue, step: StepValue, style: slider_style}, value: SliderValue" ></div><p class="minval" data-bind="text: minValue, attr:{style: minvalue_style}"></p><p class="value" data-bind="text: sliderValue, attr:{style: value_style}"></p><p class="maxval" data-bind="text: maxValue, attr:{style: maxvalue_style}"></p></div></li>', 2, 1, 6, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baserss-default-tech-rss-feed" id="default-tech-rss-feed"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><h1 class="text" data-bind="html: text, attr:{ style: text_style}"></h1><h1 class="description" data-bind="html: description, attr:{ style: text_style}"></h1></div></li>', 3, 1, 8, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-nav-status" id="default-nav-status"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 1, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label-hue-sz" id="default-label-hue-sz"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 2, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-label-licht-2" id="default-label-licht-2"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 2, 1, 4, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseinputnumber-default-bri-schlafzimmer" id="default-bri-schlafzimmer"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="slidercontainer" data-bind="attr:{style: slidercontainer_style}"><input type="range" data-bind="attr: {min: MinValue, max: MaxValue, step: StepValue, style: slider_style}, value: SliderValue" ></div><p class="minval" data-bind="text: minValue, attr:{style: minvalue_style}"></p><p class="value" data-bind="text: sliderValue, attr:{style: value_style}"></p><p class="maxval" data-bind="text: maxValue, attr:{style: maxvalue_style}"></p></div></li>', 2, 1, 6, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baserss-default-foot-rss-feed" id="default-foot-rss-feed"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><h1 class="text" data-bind="html: text, attr:{ style: text_style}"></h1><h1 class="description" data-bind="html: description, attr:{ style: text_style}"></h1></div></li>', 3, 1, 8, 6)
    
    
    
    var widgets = {}
    // Initialize Widgets
    
        widgets["default-nav-main"] = new basejavascript("default-nav-main", "", "default", {'css': {'icon_active_style': 'color: #fff;', 'icon_inactive_style': 'color: #fff;'}, 'precision': 0, 'fields': {'icon': '', 'title2': 'Home', 'icon_style': '', 'title': ''}, 'static_icons': [], 'namespace': 'default', 'widget_style': 'background: MEDIUMSLATEBLUE;', 'icon_inactive': 'mdi-home-assistant', 'icons': {'icon_active': 'fas-spinner fa-spin', 'icon_inactive': 'mdi-home-assistant'}, 'use_hass_icon': 1, 'dashboard': 'Main', 'widget_type': 'basejavascript', 'use_comma': 0, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;background: MEDIUMSLATEBLUE;'}})
    
        widgets["default-label"] = new basedisplay("default-label", "", "default", {'use_hass_icon': 1, 'css': {}, 'precision': 0, 'widget_style': 'background: MEDIUMSLATEBLUE;', 'fields': {'state_text': '', 'title2': 'Smart Home Dashboard', 'unit': '', 'value': '', 'title': 'Home Assistant'}, 'static_icons': [], 'namespace': 'default', 'title_style': 'letter-spacing: 0.35em;text-transform: uppercase;', 'title2_style': 'font-size: 300%;', 'icons': [], 'static_css': {'title_style': 'letter-spacing: 0.35em;color: #fff;text-transform: uppercase;', 'container_style': '', 'value_style': 'color: #fff;', 'unit_style': '', 'widget_style': 'background-color: #444;background: MEDIUMSLATEBLUE;', 'title2_style': 'color: #fff;font-size: 300%;', 'state_text_style': 'color: #fff;'}, 'widget_type': 'basedisplay', 'use_comma': 0})
    
        widgets["default-reload"] = new basejavascript("default-reload", "", "default", {'use_hass_icon': 1, 'css': {'icon_active_style': 'color: #fff;', 'icon_inactive_style': 'color: #fff;'}, 'precision': 0, 'fields': {'icon': '', 'title2': 'Reload', 'icon_style': '', 'title': ''}, 'static_icons': [], 'command': 'location.reload(true)', 'namespace': 'default', 'widget_style': 'background: MEDIUMSLATEBLUE;', 'icons': {'icon_active': 'fas-spinner fa-spin', 'icon_inactive': 'fas-sync'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;background: MEDIUMSLATEBLUE;'}, 'widget_type': 'basejavascript', 'use_comma': 0})
    
        widgets["default-clock"] = new baseclock("default-clock", "", "default", {'time_format': '24hr', 'use_hass_icon': 1, 'css': {}, 'precision': 0, 'fields': {'date': '', 'time': ''}, 'static_icons': [], 'namespace': 'default', 'widget_style': 'background: DARKSLATEBLUE;', 'icons': [], 'static_css': {'widget_style': 'background-color: #444;background: DARKSLATEBLUE;', 'time_style': 'color: #aa00ff;', 'date_style': 'color: #fff;'}, 'widget_type': 'baseclock', 'use_comma': 0})
    
        widgets["default-nav-weather"] = new basejavascript("default-nav-weather", "", "default", {'css': {'icon_active_style': 'color: #fff;', 'icon_inactive_style': 'color: #fff;'}, 'precision': 0, 'fields': {'icon': '', 'title2': 'Wetter', 'icon_style': '', 'title': ''}, 'static_icons': [], 'namespace': 'default', 'widget_style': 'background: DARKSLATEBLUE;', 'icon_inactive': 'mdi-weather-partlycloudy', 'icons': {'icon_active': 'fas-spinner fa-spin', 'icon_inactive': 'mdi-weather-partlycloudy'}, 'use_hass_icon': 1, 'dashboard': 'Weather', 'widget_type': 'basejavascript', 'use_comma': 0, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;background: DARKSLATEBLUE;'}})
    
        widgets["default-weather-label"] = new basedisplay("default-weather-label", "", "default", {'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'container_style': '', 'value_style': 'color: #fff;', 'unit_style': '', 'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;font-size: 200%;', 'state_text_style': 'color: #fff;'}, 'static_icons': [], 'css': {}, 'widget_type': 'basedisplay', 'use_hass_icon': 1, 'title2_style': 'font-size: 200%;', 'fields': {'state_text': '', 'title2': 'Aktuelles Wetter', 'unit': '', 'value': '', 'title': ''}, 'use_comma': 0, 'icons': [], 'precision': 0})
    
        widgets["default-temperature-now"] = new baseentitydisplay("default-temperature-now", "", "default", {'sub_entity': 'sensor.dark_sky_overnight_low_temperature_0', 'css': {'value_style': 'color: #00aaff;font-size: 250%;', 'unit_style': 'color: #00aaff;font-size: 100%;', 'text_style': 'color: #fff;font-size: 100%;'}, 'precision': 0, 'fields': {'state_text': '', 'title2': '', 'unit': '', 'value': '', 'title': 'Temperatur'}, 'icons': [], 'entity': 'sensor.dark_sky_apparent_temperature', 'namespace': 'default', 'use_hass_icon': 1, 'title2_style': 'margin-top:3px;', 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'container_style': '', 'value_style': '', 'unit_style': '', 'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;margin-top:3px;', 'state_text_style': 'background-color:inherit;color: #fff;font-size: 100%;'}, 'widget_type': 'baseentitydisplay', 'use_comma': 0, 'state_text_style': 'background-color:inherit;'})
    
        widgets["default-weather-icon-now"] = new baseiconsensor("default-weather-icon-now", "", "default", {'sub_entity': 'sensor.dark_sky_precip_probability', 'css': {'icon_style_active': ''}, 'precision': 0, 'title_entity': 'sensor.dark_sky_summary', 'fields': {'icon': '', 'state_text': '', 'title2': '', 'icon_style': '', 'title': ''}, 'icons': {'snow': {'icon': 'mdi-weather-snowy', 'style': 'color: #aaff00'}, 'partly-cloudy-day': {'icon': 'mdi-weather-partlycloudy', 'style': 'color: #aaff00'}, 'wind': {'icon': 'mdi-weather-windy', 'style': 'color: #aaff00'}, 'fog': {'icon': 'mdi-weather-fog', 'style': 'color: #aaff00'}, 'partly-cloudy-night': {'icon': 'mdi-weather-partlycloudy', 'style': 'color: #aaff00'}, 'clear-day': {'icon': 'mdi-weather-sunny', 'style': 'color: #aaff00'}, 'sleet': {'icon': 'mdi-weather-snowy-rainy', 'style': 'color: #aaff00'}, 'cloudy': {'icon': 'mdi-weather-cloudy', 'style': 'color: #aaff00'}, 'clear-night': {'icon': 'mdi-weather-night', 'style': 'color: #aaff00'}, 'rain': {'icon': 'mdi-weather-rainy', 'style': 'color: #aaff00'}}, 'entity': 'sensor.dark_sky_icon', 'namespace': 'default', 'widget_style': 'background-color:inherit;', 'title2_style': 'margin-top:3px;', 'static_icons': [], 'static_css': {'title_style': '', 'title2_style': '', 'widget_style': '', 'state_text_style': ''}, 'use_hass_icon': 1, 'widget_type': 'baseiconsensor', 'use_comma': 0, 'state_text_style': 'background-color:inherit;'})
    
        widgets["default-daily-forecast"] = new baseentitydisplay("default-daily-forecast", "", "default", {'sub_entity': '', 'css': {'value_style': 'color: #00aaff;font-size: 250%;', 'unit_style': 'color: #00aaff;font-size: 100%;', 'text_style': 'color: #fff;font-size: 100%;'}, 'precision': 0, 'widget_style': 'background-color:inherit;', 'fields': {'state_text': '', 'title2': '', 'unit': '', 'value': '', 'title': '24h Vorhersage'}, 'icons': [], 'entity': 'sensor.dark_sky_hourly_summary', 'namespace': 'default', 'title_style': 'background-color:#555;border-radius:5px;margin-top:-5px;padding:5px 0 3px;', 'static_icons': [], 'static_css': {'title_style': 'background-color:#555;color: #fff;border-radius:5px;margin-top:-5px;padding:5px 0 3px;', 'container_style': '', 'value_style': '', 'unit_style': '', 'widget_style': 'background-color:inherit;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;font-size: 100%;'}, 'use_hass_icon': 1, 'widget_type': 'baseentitydisplay', 'use_comma': 0})
    
        widgets["default-ts-rss-feed"] = new baserss("default-ts-rss-feed", "", "default", {'css': {}, 'precision': 0, 'interval': 300, 'fields': {'title2': '', 'text': '', 'description': '', 'title': ''}, 'icons': [], 'entity': 'rss.tagesschau', 'namespace': 'default', 'use_hass_icon': 1, 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'text_style': 'color: #00aaff;'}, 'show_description': 1, 'widget_type': 'baserss', 'use_comma': 0})
    
        widgets["default-nav-spacer"] = new basedisplay("default-nav-spacer", "", "default", {'namespace': 'default', 'widget_style': 'background: DARKSLATEBLUE;', 'css': {}, 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'container_style': '', 'value_style': 'color: #fff;', 'unit_style': '', 'widget_style': 'background-color: #444;background: DARKSLATEBLUE;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'widget_type': 'basedisplay', 'use_hass_icon': 1, 'fields': {'state_text': '', 'title2': '', 'unit': '', 'value': '', 'title': ''}, 'use_comma': 0, 'icons': [], 'precision': 0})
    
        widgets["default-modi-title"] = new basedisplay("default-modi-title", "", "default", {'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'container_style': '', 'value_style': 'color: #fff;', 'unit_style': '', 'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;font-size: 200%;', 'state_text_style': 'color: #fff;'}, 'static_icons': [], 'css': {}, 'widget_type': 'basedisplay', 'use_hass_icon': 1, 'title2_style': 'font-size: 200%;', 'fields': {'state_text': '', 'title2': 'Modi', 'unit': '', 'value': '', 'title': ''}, 'use_comma': 0, 'icons': [], 'precision': 0})
    
        widgets["default-kino-bool"] = new baseswitch("default-kino-bool", "", "default", {'state_active': 'on', 'css': {'icon_style_active': 'color: #aaff00;', 'icon_style_inactive': 'color: #888;'}, 'precision': 0, 'post_service_inactive': {'entity_id': 'input_boolean.kino_modus', 'service': 'homeassistant/turn_off'}, 'fields': {'icon': '', 'state_text': '', 'title2': '', 'icon_style': '', 'title': 'Kino Modus'}, 'icons': {'icon_off': 'mdi-theater', 'icon_on': 'mdi-theater'}, 'entity': 'input_boolean.kino_modus', 'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'state_text_style': 'color: #fff;'}, 'icon_off': 'mdi-theater', 'static_icons': [], 'enable': 1, 'post_service_active': {'entity_id': 'input_boolean.kino_modus', 'service': 'homeassistant/turn_on'}, 'state_inactive': 'off', 'use_hass_icon': 1, 'widget_type': 'baseswitch', 'use_comma': 0, 'icon_on': 'mdi-theater'})
    
        widgets["default-wakeup-bool"] = new baseswitch("default-wakeup-bool", "", "default", {'state_active': 'on', 'css': {'icon_style_active': 'color: #aaff00;', 'icon_style_inactive': 'color: #888;'}, 'precision': 0, 'post_service_inactive': {'entity_id': 'input_boolean.wakeup_enabled', 'service': 'homeassistant/turn_off'}, 'fields': {'icon': '', 'state_text': '', 'title2': '', 'icon_style': '', 'title': 'Wake-Up Modus'}, 'icons': {'icon_off': 'mdi-theme-light-dark', 'icon_on': 'mdi-theme-light-dark'}, 'entity': 'input_boolean.wakeup_enabled', 'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'state_text_style': 'color: #fff;'}, 'icon_off': 'mdi-theme-light-dark', 'static_icons': [], 'enable': 1, 'post_service_active': {'entity_id': 'input_boolean.wakeup_enabled', 'service': 'homeassistant/turn_on'}, 'state_inactive': 'off', 'use_hass_icon': 1, 'widget_type': 'baseswitch', 'use_comma': 0, 'icon_on': 'mdi-theme-light-dark'})
    
        widgets["default-wakeup-weekend"] = new baseswitch("default-wakeup-weekend", "", "default", {'state_active': 'on', 'css': {'icon_style_active': 'color: #aaff00;', 'icon_style_inactive': 'color: #888;'}, 'precision': 0, 'post_service_inactive': {'entity_id': 'input_boolean.wakeup_weekend', 'service': 'homeassistant/turn_off'}, 'fields': {'icon': '', 'state_text': '', 'title2': '', 'icon_style': '', 'title': 'Wake-Up Wochenende'}, 'icons': {'icon_off': 'mdi-calendar-multiselect', 'icon_on': 'mdi-calendar-multiselect'}, 'entity': 'input_boolean.wakeup_weekend', 'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'state_text_style': 'color: #fff;'}, 'icon_off': 'mdi-calendar-multiselect', 'static_icons': [], 'enable': 1, 'post_service_active': {'entity_id': 'input_boolean.wakeup_weekend', 'service': 'homeassistant/turn_on'}, 'state_inactive': 'off', 'use_hass_icon': 1, 'widget_type': 'baseswitch', 'use_comma': 0, 'icon_on': 'mdi-calendar-multiselect'})
    
        widgets["default-world-rss-feed"] = new baserss("default-world-rss-feed", "", "default", {'css': {}, 'precision': 0, 'interval': 300, 'fields': {'title2': '', 'text': '', 'description': '', 'title': 'World News'}, 'icons': [], 'entity': 'rss.cnn-world', 'namespace': 'default', 'use_hass_icon': 1, 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'text_style': 'color: #00aaff;'}, 'show_description': 1, 'widget_type': 'baserss', 'use_comma': 0})
    
        widgets["default-hue-scene-label"] = new basedisplay("default-hue-scene-label", "", "default", {'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'container_style': '', 'value_style': 'color: #fff;', 'unit_style': '', 'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;font-size: 200%;', 'state_text_style': 'color: #fff;'}, 'static_icons': [], 'css': {}, 'widget_type': 'basedisplay', 'use_hass_icon': 1, 'title2_style': 'font-size: 200%;', 'fields': {'state_text': '', 'title2': 'Hue Szenen', 'unit': '', 'value': '', 'title': ''}, 'use_comma': 0, 'icons': [], 'precision': 0})
    
        widgets["default-scene-select"] = new baseselect("default-scene-select", "", "default", {'sub_entity': '', 'css': {}, 'precision': 0, 'post_service': {'entity_id': 'input_select.bedroom_scenes', 'service': 'input_select/select_option'}, 'fields': {'state_text': '', 'selectedoption': '', 'title2': '', 'inputoptions': [], 'title': 'Szene wählen'}, 'icons': [], 'entity': 'input_select.bedroom_scenes', 'namespace': 'default', 'use_hass_icon': 1, 'static_icons': {}, 'static_css': {'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;', 'selectcontainer_style': '', 'title_style': 'color: #fff;', 'select_style': 'background-color: #999;color:black;', 'state_text_style': ''}, 'widget_type': 'baseselect', 'use_comma': 0})
    
        widgets["default-room-select"] = new baseselect("default-room-select", "", "default", {'sub_entity': '', 'css': {}, 'precision': 0, 'post_service': {'entity_id': 'input_select.lamp', 'service': 'input_select/select_option'}, 'fields': {'state_text': '', 'selectedoption': '', 'title2': '', 'inputoptions': [], 'title': 'Zimmer'}, 'icons': [], 'entity': 'input_select.lamp', 'namespace': 'default', 'use_hass_icon': 1, 'static_icons': {}, 'static_css': {'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;', 'selectcontainer_style': '', 'title_style': 'color: #fff;', 'select_style': 'background-color: #999;color:black;', 'state_text_style': ''}, 'widget_type': 'baseselect', 'use_comma': 0})
    
        widgets["default-hn-rss-feed"] = new baserss("default-hn-rss-feed", "", "default", {'css': {}, 'precision': 0, 'interval': 300, 'fields': {'title2': '', 'text': '', 'description': '', 'title': 'HN RSS feed news.ycombinator.com'}, 'icons': [], 'text_style': 'font-size: 16pt;', 'namespace': 'default', 'use_hass_icon': 1, 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'text_style': 'color: #00aaff;font-size: 16pt;'}, 'entity': 'rss.hn', 'widget_type': 'baserss', 'use_comma': 0})
    
        widgets["default-label-hue-wz"] = new basedisplay("default-label-hue-wz", "", "default", {'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'container_style': '', 'value_style': 'color: #fff;', 'unit_style': '', 'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;font-size: 200%;', 'state_text_style': 'color: #fff;'}, 'static_icons': [], 'css': {}, 'widget_type': 'basedisplay', 'use_hass_icon': 1, 'title2_style': 'font-size: 200%;', 'fields': {'state_text': '', 'title2': 'Wohnzimmer', 'unit': '', 'value': '', 'title': ''}, 'use_comma': 0, 'icons': [], 'precision': 0})
    
        widgets["default-label-licht"] = new baselight("default-label-licht", "", "default", {'post_service_inactive': {'entity_id': 'light.wohnzimmer', 'service': 'homeassistant/turn_off'}, 'css': {'icon_style_active': 'color: #aaff00;', 'icon_style_inactive': 'color: #888;'}, 'precision': 0, 'fields': {'units': '%', 'icon': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'Licht', 'state_text': ''}, 'icons': {'icon_off': 'mdi-sofa', 'icon_on': 'mdi-sofa'}, 'entity': 'light.wohnzimmer', 'namespace': 'default', 'post_service_active': {'entity_id': 'light.wohnzimmer', 'service': 'homeassistant/turn_on'}, 'icon_off': 'mdi-sofa', 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'level_up_style': 'color: #888;'}, 'use_hass_icon': 1, 'widget_type': 'baselight', 'use_comma': 0, 'icon_on': 'mdi-sofa'})
    
        widgets["default-bri-wohnzimmer"] = new baseinputnumber("default-bri-wohnzimmer", "", "default", {'css': {}, 'precision': 0, 'post_service': {'entity_id': 'input_number.brightness_wohnzimmer', 'service': 'input_number/set_value'}, 'fields': {'MaxValue': '', 'title': 'Helligkeit', 'maxValue': '', 'title2': '', 'SliderValue': '', 'minValue': '', 'sliderValue': '', 'MinValue': '', 'StepValue': ''}, 'icons': [], 'entity': 'input_number.brightness_wohnzimmer', 'namespace': 'default', 'static_css': {'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;', 'minvalue_style': 'color: #fff;', 'title_style': 'color: #fff;', 'maxvalue_style': 'color: #fff;', 'value_style': 'color: #fff;', 'slidercontainer_style': '', 'slider_style': '-webkit-appearance: none;'}, 'static_icons': [], 'use_hass_icon': 1, 'widget_type': 'baseinputnumber', 'use_comma': 0})
    
        widgets["default-tech-rss-feed"] = new baserss("default-tech-rss-feed", "", "default", {'css': {}, 'precision': 0, 'interval': 300, 'fields': {'title2': '', 'text': '', 'description': '', 'title': 'CNN Technology'}, 'icons': [], 'entity': 'rss.cnn-tech', 'namespace': 'default', 'use_hass_icon': 1, 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'text_style': 'color: #00aaff;'}, 'show_description': 1, 'widget_type': 'baserss', 'use_comma': 0})
    
        widgets["default-nav-status"] = new basejavascript("default-nav-status", "", "default", {'css': {'icon_active_style': 'color: #fff;', 'icon_inactive_style': 'color: #fff;'}, 'precision': 0, 'fields': {'icon': '', 'title2': 'Status', 'icon_style': '', 'title': ''}, 'static_icons': [], 'namespace': 'default', 'widget_style': 'background: DARKSLATEBLUE;', 'icon_inactive': 'mdi-information-outline', 'icons': {'icon_active': 'fas-spinner fa-spin', 'icon_inactive': 'mdi-information-outline'}, 'use_hass_icon': 1, 'dashboard': 'Status', 'widget_type': 'basejavascript', 'use_comma': 0, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;background: DARKSLATEBLUE;'}})
    
        widgets["default-label-hue-sz"] = new basedisplay("default-label-hue-sz", "", "default", {'namespace': 'default', 'static_css': {'title_style': 'color: #fff;', 'container_style': '', 'value_style': 'color: #fff;', 'unit_style': '', 'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;font-size: 200%;', 'state_text_style': 'color: #fff;'}, 'static_icons': [], 'css': {}, 'widget_type': 'basedisplay', 'use_hass_icon': 1, 'title2_style': 'font-size: 200%;', 'fields': {'state_text': '', 'title2': 'Schlafzimmer', 'unit': '', 'value': '', 'title': ''}, 'use_comma': 0, 'icons': [], 'precision': 0})
    
        widgets["default-label-licht-2"] = new baselight("default-label-licht-2", "", "default", {'post_service_inactive': {'entity_id': 'light.schlafzimmer', 'service': 'homeassistant/turn_off'}, 'css': {'icon_style_active': 'color: #aaff00;', 'icon_style_inactive': 'color: #888;'}, 'precision': 0, 'fields': {'units': '%', 'icon': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'Licht', 'state_text': ''}, 'icons': {'icon_off': 'mdi-hotel', 'icon_on': 'mdi-hotel'}, 'entity': 'light.schlafzimmer', 'namespace': 'default', 'post_service_active': {'entity_id': 'light.schlafzimmer', 'service': 'homeassistant/turn_on'}, 'icon_off': 'mdi-hotel', 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'level_up_style': 'color: #888;'}, 'use_hass_icon': 1, 'widget_type': 'baselight', 'use_comma': 0, 'icon_on': 'mdi-hotel'})
    
        widgets["default-bri-schlafzimmer"] = new baseinputnumber("default-bri-schlafzimmer", "", "default", {'css': {}, 'precision': 0, 'post_service': {'entity_id': 'input_number.brightness_schlafzimmer', 'service': 'input_number/set_value'}, 'fields': {'MaxValue': '', 'title': 'Helligkeit', 'maxValue': '', 'title2': '', 'SliderValue': '', 'minValue': '', 'sliderValue': '', 'MinValue': '', 'StepValue': ''}, 'icons': [], 'entity': 'input_number.brightness_schlafzimmer', 'namespace': 'default', 'static_css': {'widget_style': 'background-color: #444;', 'title2_style': 'color: #fff;', 'minvalue_style': 'color: #fff;', 'title_style': 'color: #fff;', 'maxvalue_style': 'color: #fff;', 'value_style': 'color: #fff;', 'slidercontainer_style': '', 'slider_style': '-webkit-appearance: none;'}, 'static_icons': [], 'use_hass_icon': 1, 'widget_type': 'baseinputnumber', 'use_comma': 0})
    
        widgets["default-foot-rss-feed"] = new baserss("default-foot-rss-feed", "", "default", {'css': {}, 'precision': 0, 'interval': 300, 'fields': {'title2': '', 'text': '', 'description': '', 'title': 'Football'}, 'icons': [], 'entity': 'rss.cnn-foot', 'namespace': 'default', 'use_hass_icon': 1, 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'text_style': 'color: #00aaff;'}, 'show_description': 1, 'widget_type': 'baserss', 'use_comma': 0})
    

    // Setup click handler to cancel timeout navigations

    $( ".gridster" ).click(function(){
        clearTimeout(myTimeout);
        if (myTimeoutSticky) {
            myTimeout = setTimeout(function() { navigate(myTimeoutUrl); }, myTimeoutDelay);
        }
    });

    // Set up timeout

    var myTimeout;
    var myTimeoutUrl;
    var myTimeoutDelay;
    var myTimeoutSticky = 0;

    if (location.search != "")
    {
        var query = location.search.substr(1);
        var result = {};
        query.split("&").forEach(function(part) {
        var item = part.split("=");
        result[item[0]] = decodeURIComponent(item[1]);
        });

        if ("timeout" in result && "return" in result)
        {
            url = result.return
            argcount = 0
            for (arg in result)
            {
                if (arg != "timeout" && arg != "return" && arg != "sticky")
                {
                    if (argcount == 0)
                    {
                        url += "?";
                    }
                    else
                    {
                        url += "?";
                    }
                    argcount ++;
                    url += arg + "=" + result[arg]
                }
            }
            if ("sticky" in result)
            {
                myTimeoutSticky = (result.sticky == "1");
            }
            myTimeoutUrl = url;
            myTimeoutDelay = result.timeout * 1000;
            myTimeout = setTimeout(function() { navigate(url); }, result.timeout * 1000);
        }
    }

    // Start listening for HA Events
    if (location.protocol == 'https:')
    {
        wsprot = "wss:"
    }
    else
    {
        wsprot = "ws:"
    }
    var stream_url = wsprot + '//' + location.host + '/stream'
    ha_status(stream_url, "Main Panel", widgets);

});